Эпик Корзина -  PR#2
Georgii-N/YPTrueNFTMarketplace pull request #98
Opened 2023-08-15 16:28 UTC by Dkrshn

Архитектура MVVM:

Доска с задачами - https://github.com/users/Georgiy-N/projects/1/views/1

Декомпозиция задач - https://github.com/Georgiy-N/YPTrueNFTMarketplace/blob/develop/Docs/CartDecomposition.md

сформирован UI всех экранов;
реализовна архитектура MVVM;
реализована работа с сетью на загрузку заказа и доступных валют;
реализован функционал удаления карточки товара с помощью PUT запросов в сеть;
добавлена сортировка корзины;
добавлена обработка ошибок сети;
исправлены замечания предидущего ревью

2023-08-17 09:01 UTC, protos17 requested changes

2023-08-17 09:01 UTC, protos17 commented on FakeNFT/Services/AnalyticsService.swift
> +final class AnalyticsService {
Класс сделан, но в коде нигде данные аналитики не отправляются

2023-08-17 09:01 UTC, protos17 commented on FakeNFT/Services/DataProvider/DataProvider.swift
> +    let networkClient = DefaultNetworkClient()
Рекомендую указать как private

2023-08-17 09:01 UTC, protos17 commented on FakeNFT/Services/DataProvider/DataProvider.swift
> +             // let request = GetOrderPaymentRequest(currencyId: currencyId)
Рекомендую удалить

2023-08-17 09:01 UTC, protos17 commented on FakeNFT/Services/UserDefaultsService.swift
> +class UserDefaultsService {
Класс без наследования рекомендую указать как final

2023-08-21 01:09 UTC, Dkrshn commented
@protos17 привет. 
1. Почему мой 3й ПР проверяется больше заложенного по регламенту времени? После твоих замечаний я своевременно вношу изменения и ПР снова уходит на 2-3 дня проверки. Как я должен поддерживать сроки с командой? На сколько я знаю, Практикум гарантирует ревью за 24 часа. Кто мне наверстает упущенное время и сдаст за меня проект?

2. В твоих крайних замечаниях есть пункты про экран регистрации/авторизации. На сколько я знаю, сейчас я сдаю свой эпик. А ты как я понял, не допускаешь к мерджу в том числе из-за этих замечаний. Это ок? Почему бы их не проверять в финальной версии? Или проверить, но не делать эти пункты основными, из-за которого проходит допуск/не допуск. 

3. По поводу сортировки. Где в документации написано, что при закрытии алерта товары не должны удалятся из корзины? где на макете в фигме эта логика отображена? Если этого нигде нет, можно не выдумывать условия работоспособности?
Если ты хочешь, посоветовать как должно это работать, то можешь четче формулировать мысли? все твои последние замечания по этому пункту выглядят так: "при нажатии на кнопку закрыть товары удаляются" - если в доке ничего про это нет я как должен понять это ошибка или рекомендация к действию?

2023-08-21 20:13 UTC, protos17 approved these changes

2023-08-21 20:13 UTC, protos17 commented on FakeNFT/Application/TabBarController.swift
> +        if UserDefaultsService.shared.getAgreement() == false {
Можно опустить false:

if !UserDefaultsService.shared.getAgreement() {
...

2023-08-21 20:13 UTC, protos17 commented on FakeNFT/Scenes /Cart/PaymentFlow/SuccessfulPaymentViewController.swift
> +    func tryLoadOrderPay() {
Рекомендую указать как private

2023-08-22 08:24 UTC, merged